name: On-demand test

on:
    workflow_dispatch:
        inputs:
            ref:
                required: true
                description: sha or branch name to deploy
                type: string
                default: 'main'

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v3.5.2
            with:
                ref: ${{ github.event.inputs.ref }}
          - name: Set vars
            id: vars
            env:
              MESSAGE: ${{ github.event.inputs.ref }}
            run: echo "sha_short=$(git rev-parse --short=8 ${{ github.event.inputs.ref }})" >> $GITHUB_OUTPUT



